language: java
jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

install:
  - npm install -g yarn
  - npm install

script:
  - yarn run lint
  - yarn run test
  - ./gradlew check

after_success:
  - yarn run codecov -cF javascript
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash) -cF java

  - yarn run codacy
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml