language: java
sudo: false

addons:
  postgresql: "9.4"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install -g yarn
  - npm install

script:
  - yarn run lint
  - yarn run test
  - gradle jacocoTestCoverageVerification

after_success:
  - yarn run codecov -cF javascript
  - gradle jacocoTestReport
  - bash <(curl -s https://codecov.io/bash) -cF java
