export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS'

export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS'
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE'

export const SUBMIT_GAME_SUCCESS = 'SUBMIT_GAME_SUCCESS'
export const SUBMIT_GAME_FAILURE = 'SUBMIT_GAME_FAILURE'

export const SET_IS_FETCHING = 'SET_IS_FETCHING'
export const CLEAR_IS_FETCHING = 'CLEAR_IS_FETCHING'
export const SET_IS_SAVING = 'SET_IS_SAVING'

export const SELECT_GAME = 'SELECT_GAME'
